// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "pzuS02B2J]r[(67[eV4,":
            case "jhsdnci":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . 3 3 . . . . . . . . 
. . . . . 3 . . . . . . . . . . 
. . . . 3 . . . . . . . . . . . 
. . . . 3 . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image1":
            case "myImage":return img`
....................
....................
....................
.......222222.......
......22222222......
......ff.22.ff......
......ffb22bff......
......ff.22.ff......
.........22.........
........2222........
.......222222.......
.......225522.......
.......25cc52.......
.......251152.......
.......251152.......
.......225522.......
.......225522.......
.......225522.......
........5555........
......ff.55.ff......
......ffbccbff......
......ff8888ff......
........8888........
....................
....................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
